image: Visual Studio 2019
version: '{build}'
skip_tags: true

clone_depth: 10
branches:
  only:
    - main
  except:
    - gh-pages

install:
  - cmd: git config core.autocrlf
  - cmd: .\mvnw.cmd --version
  - cmd: java -version

cache:
  - C:\Users\appveyor\.m2
  - .mvn\wrapper

matrix:
  fast_finish: true

environment:
  global:
    CMD: " "
    # https://stackoverflow.com/questions/42024619/maven-build-gets-connection-reset-when-downloading-artifacts
    MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.retryHandler.count=3"
  matrix:
    # sevntu (JDK21)
    - JAVA_HOME: C:\Program Files\Java\JDK21
      DESC: "sevntu (JDK21)"
      CMD: "./.ci/validation.cmd sevntu"
    # run checkstyle (JDK21)
    - JAVA_HOME: C:\Program Files\Java\JDK21
      DESC: "run checkstyle (JDK21)"
      CMD: "./.ci/validation.cmd run_checkstyle"
    # verify without checkstyle (JDK21)
    - JAVA_HOME: C:\Program Files\Java\JDK21
      DESC: "verify without checkstyle (JDK21)"
      CMD: "./.ci/validation.cmd verify_without_checkstyle"
    # site, without verify (JDK21)
    - JAVA_HOME: C:\Program Files\Java\JDK21
      DESC: "site, without verify (JDK21)"
      CMD: "./.ci/validation.cmd site_without_verify"

build_script:
  - ps: |
      $RUN_JOB=1
      if ($RUN_JOB -eq 1) {
        $Expr = (get-content env:CMD)
        Write-Host "CMD: $Expr"
        Invoke-Expression $Expr
        Write-Host "CMD exited with exit code $LastExitCode"
        if ($LastExitCode -ne 0) {
          exit $LastExitCode
        }
      } else {
        Write-Host "build is skipped ..."
      }
  - ps: ./.ci/validation.cmd git_diff
  - ps: echo "Size of caches (bytes):"
  - ps: Get-ChildItem -Recurse 'C:\Users\appveyor\.m2' | Measure-Object -Property Length -Sum
