os: Windows Server 2012
version: '{build}'
skip_tags: true
skip_commits:
  files:
    - .ci/
    - .github/
    - travis.yml
    - .circleci/
    - distelli-manifest.yml
    - fast-forward-merge.sh
    - LICENSE
    - LICENSE.apache20
    - README.md
    - release.sh
    - RIGHTS.antlr
    - shippable.yml
    - shippable.sh
    - wercker.yml
    - wercker.sh
    - codeship-

clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
init:
  - git config --global core.autocrlf true
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven\apache-maven-3.2.5" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5
  - cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: git config --global core.autocrlf
  - cmd: mvn --version
  - cmd: java -version

cache:
  - C:\maven\apache-maven-3.2.5
  - C:\Users\appveyor\.m2

matrix:
  fast_finish: true

environment:
  global:
    CMD1: " "
    CMD2: " "
    CMD3: " "
    CMD4: " "
    CMD5: " "
    CMD6: " "
    CMD7: " "
    CMD8: " "
    CMD9: " "
    CMD10: " "
  # We do matrix as AppVeyor could fail to finish simple "mvn verify"
  #    if he loose maven cache (happens from time to time)
  matrix:
    # checkstyle and sevntu.checkstyle
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      DESC: "checkstyle and sevntu.checkstyle"
      CMD1: "mvn -e verify -DskipTests -DskipITs -Dpmd.skip=true -Dspotbugs.skip=true -Djacoco.skip=true -Dxml.skip=true"
    # verify without checkstyle (JDK8)
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      DESC: "verify without checkstyle (JDK8)"
      CMD1: "mvn -e verify -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true"
    # verify without checkstyle (JDK9)
    - JAVA_HOME: C:\Program Files\Java\jdk9
      DESC: "verify without checkstyle (JDK9)"
      CMD1: "mvn -e verify -Dcheckstyle.ant.skip=true -Dcheckstyle.skip=true"
    # site, without verify (JDK8)
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      DESC: "site, without verify (JDK8)"
      CMD1: "mvn -e -Pno-validations site"
    # site, without verify (JDK9)
    - JAVA_HOME: C:\Program Files\Java\jdk9
      DESC: "site, without verify (JDK9)"
      CMD1: "mvn -e -Pno-validations site"

build_script:
  - ps: >
       (get-content env:CMD1)
       + (get-content env:CMD2)
       + (get-content env:CMD3)
       + (get-content env:CMD4)
       + (get-content env:CMD5)
       + (get-content env:CMD6)
       + (get-content env:CMD7)
       + (get-content env:CMD8)
       + (get-content env:CMD9)
       + (get-content env:CMD10)
       | Out-File appveyor.cmd -encoding ASCII
  - ps: get-content appveyor.cmd
  # We need to use cmd there as ps1 is failing each time error output appear from any command line
  - appveyor.cmd
