version: 1.0

linter: jetbrains/qodana-jvm-community:2025.3
projectJDK: "21"

failureConditions:
  severityThresholds:
    any: 0

profile:
  path: intellij-idea-inspections.xml

exclude:
  - name: All
    paths:
      - target/
      - bin/
      - .ci-temp/

      - src/test/resources/
      - src/it/resources/
      - src/site/resources/js/google-analytics.js
      - src/site/resources/styleguides/

      - config/intellij-idea-inspections.properties
      - config/site-2.0.0.xsd
      - config/projects-to-test/openjdk-projects-to-test-on.config
      - config/projects-for-no-exception-javadoc.config
      - config/idea.properties

      - .settings/
      - .classpath
      - .project
      - .idea/

      - .circleci/config.yml
      - .ci/*.config
      - .ci/pitest-survival-check-xml.groovy
      - .ci/checker-framework.groovy
      - .ci/codenarc.groovy
      - .ci/error-prone-check.groovy

      - .mvn/

      - src/xdocs-examples/resources/
      - src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/ParseTreeBuilder.java
      - src/test/java/com/puppycrawl/tools/checkstyle/grammar/javadoc/ParseTreeBuilder.java

      - docs/GRAMMAR_UPDATES.md
