#############################################################################
# GitHub Action to bump release version
#
#############################################################################
name: "R: Bump version/Update Milestone"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'POM version without (-SNAPSHOT)'
        required: true
permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  printInputs:
    name: Print Input
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Latest Version: ${{ inputs.version }}"
  bump:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v6

      - name: Setup local maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Modify File
        run: |
          ./.ci/bump-version.sh ${{ inputs.version }}

      - name: Push commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "minor: Bump version to ${{ inputs.version }}-SNAPSHOT"
          git push

      - name: GitHub Milestone
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          .ci/update-github-milestone.sh ${{ inputs.version }}
