#####################################################################################
# GitHub Action to test performance regression.
#
# Workflow starts when:
# 1) push to master
# 2) PR created or pushed
#
#####################################################################################
name: Check-Performance-Regression

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.repository == 'checkstyle/checkstyle'
    strategy:
      matrix:
        target:
          - java
          - javadoc
        include:
          - target: java
            BASELINE_SECONDS: 390.70
            CONFIG_FILE: './config/benchmark-config.xml'
          - target: javadoc
            BASELINE_SECONDS: 424.59
            CONFIG_FILE: './config/benchmark-javadoc-config.xml'
    runs-on: ubuntu-latest
    env:
      BASELINE_SECONDS: ${{ matrix.BASELINE_SECONDS }}
      CONFIG_FILE: ${{ matrix.CONFIG_FILE }}
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Checkout Pull Request Code
        uses: actions/checkout@v6

      - name: Clone JDK 25 Repo
        uses: actions/checkout@v6
        with:
          repository: openjdk/jdk25u
          path: ./.ci-temp/jdk25

      - name: Setup local maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Run performance test
        run: |
          ./.ci/check-performance-regression.sh "$BASELINE_SECONDS" "$CONFIG_FILE"
