name: Checker-Framework

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checker-framework:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - checker-framework-nullness-optional-interning
          - checker-framework-methods-resource-fenum
          - checker-framework-lock-tainting
          - checker-framework-index
          - checker-framework-formatter
          - checker-framework-signature-gui-units-init
          - checker-framework-regex-property-key-compiler-message
          - checker-framework-purity-value-returns

    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install groovy
        run: sudo apt install groovy
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute checker framework
        run: groovy ./.ci/checker-framework.groovy ${{ matrix.profile }} || true
        env:
          MAVEN_OPTS: "-Xmx4g"
