name: Checker

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    if: github.repository == 'checkstyle/checkstyle'
    strategy:
      fail-fast: false
      matrix:
        profile: [
          nullness-optional-interning,
          methods-resource-fenum,
          lock-tainting,
          formatter,
          signature-gui-units-init,
          regex-property-key-compiler-message,
          purity-value-returns,
        ]

    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Groovy using SDKMAN
        run: |
          curl --fail-with-body -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy 4.0.24
          echo "GROOVY_HOME=$HOME/.sdkman/candidates/groovy/current" >> "$GITHUB_ENV"
          echo "$HOME/.sdkman/candidates/groovy/current/bin" >> "$GITHUB_PATH"

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup local maven cache
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Execute checker framework
        env:
          MAVEN_OPTS: "-Xmx4g"
        run: groovy ./.ci/checker-framework.groovy checker-${{ matrix.profile }}

      - name: Git Diff on fail
        if: failure()
        run: ./.ci/print-diff-as-patch.sh target/checker-${{ matrix.profile }}.patch

      - name: Share patch as artifact to apply on local
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: checker-${{ matrix.profile }}-patch
          path: target/checker-${{ matrix.profile }}.patch
          retention-days: 7
