#############################################################################
# GitHub Action to Copy Site to SourceForge.
#
#############################################################################
name: "R: Copy Site to SourceForge"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version without (-SNAPSHOT)'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  copy-site:
    name: Copy site to sourceforge for ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Configure SSH
        env:
          SF_SSH_KEY: ${{ secrets.SF_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          eval "$(ssh-agent -s)"
          echo "$SF_SSH_KEY" > ~/.ssh/private_sourceforge_key
          chmod 400 ~/.ssh/private_sourceforge_key
          ssh-add ~/.ssh/private_sourceforge_key
          ssh-keyscan -t ed25519 shell.sourceforge.net >> ~/.ssh/known_hosts
          ssh-keyscan -t ed25519 web.sourceforge.net >> ~/.ssh/known_hosts

      - name: Run Shell Script
        env:
          SF_USER: ${{ secrets.SF_USER }}
        run: |
          ./.ci/copy-site-to-sourceforge.sh ${{ inputs.version }}
