name: Error-Prone

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  error-prone:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Groovy using SDKMAN
        run: |
          curl --fail-with-body -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy 5.0.0
          echo "GROOVY_HOME=$HOME/.sdkman/candidates/groovy/current" >> "$GITHUB_ENV"
          echo "$HOME/.sdkman/candidates/groovy/current/bin" >> "$GITHUB_PATH"

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup local maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Execute Error-Prone on compile phase
        run: groovy ./.ci/error-prone-check.groovy compile

      # Require to compile again in case previous step fails and sources are not compiled
      - name: Do a clean compile
        if: always()
        run: mvn -e --no-transfer-progress clean compile

      - name: Execute Error-Prone on test-compile phase
        if: always()
        run: groovy ./.ci/error-prone-check.groovy test-compile
