#####################################################################################
# GitHub Action to format specific files by google-java-format.
#
# Workflow starts when:
# 1) push to master
# 2) PR created or pushed
#
#####################################################################################
name: Google-Java-Format

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  VERSION: 1.26.0

jobs:
  test:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Checkout Pull Request Code
        uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'google/google-java-format'
          tag: "v${{env.VERSION}}"
          fileName: "google-java-format-${{env.VERSION}}-all-deps.jar"
          out-file-path: '.ci-temp'

      - name: Run Formatting
        run: |
          ./.ci/google-java-format.sh .ci-temp/google-java-format-${{env.VERSION}}-all-deps.jar
          ./.ci/validation.sh git-diff
