#############################################################################
# GitHub Action to Create New Milestone and issue in Other Repositories.
#
#############################################################################
name: "R: Close/Create Milestone, Upload '-all' jar, Create issues"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true

permissions:
  contents: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  creation:
    name: Creation-New Milestone/Issue" for ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download ncal
        run: |
          sudo apt-get install ncal
      - name: Setup local maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
      - name: Close/Create Milestone
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./.ci/close-create-milestone.sh

      - name: Upload '-all' jar
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./.ci/upload-all-jar.sh ${{ inputs.version }}

      - name: Creation of issue in other Repositories
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          ./.ci/creation-of-issue-in-other-repos.sh ${{ inputs.version }}
