name: "no-exception testing"

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # this execution should stay on GitHub actions due to time/ memory limits in other CI
  no-exception-openjdk17:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Groovy using SDKMAN
        run: |
          curl --fail-with-body -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy 4.0.24
          echo "GROOVY_HOME=$HOME/.sdkman/candidates/groovy/current" >> "$GITHUB_ENV"
          echo "$HOME/.sdkman/candidates/groovy/current/bin" >> "$GITHUB_PATH"

      - name: Checkout repository
        uses: actions/checkout@v6

      - run: .ci/no-exception-test.sh openjdk17-with-checks-nonjavadoc-error
  # this execution should stay on GitHub actions due to time/ memory limits in other CI
  no-exception-openjdk19:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Groovy using SDKMAN
        run: |
          curl --fail-with-body -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy 4.0.24
          echo "GROOVY_HOME=$HOME/.sdkman/candidates/groovy/current" >> "$GITHUB_ENV"
          echo "$HOME/.sdkman/candidates/groovy/current/bin" >> "$GITHUB_PATH"

      - name: Checkout repository
        uses: actions/checkout@v6

      - run: .ci/no-exception-test.sh openjdk19-with-checks-nonjavadoc-error
  # this execution should stay on GitHub actions due to time/ memory limits in other CI
  no-exception-openjdk20:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Groovy using SDKMAN
        run: |
          curl --fail-with-body -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy 4.0.24
          echo "GROOVY_HOME=$HOME/.sdkman/candidates/groovy/current" >> "$GITHUB_ENV"
          echo "$HOME/.sdkman/candidates/groovy/current/bin" >> "$GITHUB_PATH"

      - name: Checkout repository
        uses: actions/checkout@v6

      - run: .ci/no-exception-test.sh openjdk20-with-checks-nonjavadoc-error
  # this execution should stay on GitHub actions due to time/ memory limits in other CI
  no-exception-openjdk25:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Groovy using SDKMAN
        run: |
          curl --fail-with-body -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy 4.0.24
          echo "GROOVY_HOME=$HOME/.sdkman/candidates/groovy/current" >> "$GITHUB_ENV"
          echo "$HOME/.sdkman/candidates/groovy/current/bin" >> "$GITHUB_PATH"

      - name: Checkout repository
        uses: actions/checkout@v6

      - run: .ci/no-exception-test.sh openjdk25-with-checks-nonjavadoc-error
