name: "no-exception testing"

on:
  pull_request:
    branches: [ master ]

jobs:
  # this execution should stay on GitHub actions due to time/ memory limits in other CI
  no-exception-openjdk17:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install dependencies
      run: sudo apt install groovy

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install checkstyle
      run: mvn -e --no-transfer-progress clean install -Pno-validations

    - run: .ci/no-exception-test.sh openjdk17-with-checks-nonjavadoc-error
