name: "no-exception testing"

on:
  pull_request:
    branches: [ master ]

jobs:
  no-exception-lucene-and-others-javadoc:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install dependencies
      run: sudo apt install groovy

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install checkstyle
      run: mvn -e --no-transfer-progress clean install -Pno-validations

    - run: ./.ci/no-exception-test.sh no-exception-lucene-and-others-javadoc

  no-exception-cassandra-storm-tapestry-javadoc:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install dependencies
      run: sudo apt install groovy

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install checkstyle
      run: mvn -e --no-transfer-progress clean install -Pno-validations

    - run: ./.ci/no-exception-test.sh no-exception-cassandra-storm-tapestry-javadoc

  no-exception-hadoop-apache-groovy-scouter-javadoc:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install dependencies
      run: sudo apt install groovy

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install checkstyle
      run: mvn -e --no-transfer-progress clean install -Pno-validations

    - run: ./.ci/no-exception-test.sh no-exception-hadoop-apache-groovy-scouter-javadoc

  no-error-xwiki:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install dependencies
      run: sudo apt install groovy

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install checkstyle
      run: mvn -e --no-transfer-progress clean install -Pno-validations

    - run: ./.ci/validation.sh no-error-xwiki

  no-exception-only-javadoc:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install dependencies
      run: sudo apt install groovy

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install checkstyle
      run: mvn -e --no-transfer-progress clean install -Pno-validations

    - run: ./.ci/no-exception-test.sh no-exception-only-javadoc

  no-exception-openjdk14:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install dependencies
      run: sudo apt install groovy

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install checkstyle
      run: mvn -e --no-transfer-progress clean install -Pno-validations

    - run: .ci/no-exception-test.sh openjdk14-with-checks-nonjavadoc-error