#############################################################################
# GitHub Action to Publish Release Notes GitHub Page.
#
#############################################################################
name: "R: Publish GitHub Page"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish releasenotes GitHub Page ${{ inputs.version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Setup local maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
      - name: Run Shell Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.ci/update-github-page.sh ${{ inputs.version }}
