#############################################################################
# GitHub Action to Copy github.io to sourceforge.org.
#
#############################################################################
name: "R: Copy github.io to sourceforge.org"
run-name: "R: Copy github.io to sourceforge.org ${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'POM version without (-SNAPSHOT)'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  copy-github-io-to-sourceforge:
    name: Copy github.io to sourceforge.org ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v6

      - name: Configure SSH
        env:
          SF_SSH_KEY: ${{ secrets.SF_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          eval "$(ssh-agent -s)"
          echo "$SF_SSH_KEY" > ~/.ssh/private_sourceforge_key
          chmod 400 ~/.ssh/private_sourceforge_key
          ssh-add ~/.ssh/private_sourceforge_key
          ssh-keyscan -t ed25519 shell.sourceforge.net >> ~/.ssh/known_hosts
          ssh-keyscan -t ed25519 web.sourceforge.net >> ~/.ssh/known_hosts

      - name: Run Shell Script
        env:
          SF_USER: ${{ secrets.SF_USER }}
        run: |
          ./.ci/release-copy-github-io-to-sourceforge.sh ${{ inputs.version }}
