#############################################################################
# GitHub Action to Update GitHub.io.
#
#############################################################################
name: "R: Update GitHub.io"
run-name: "R: Update GitHub.io ${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'POM version without (-SNAPSHOT)'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}
    -${{ github.event.pull_request.number || github.ref }}-update-github-io
  cancel-in-progress: true

jobs:
  update-github-io:
    name: Update GitHub.io ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/checkstyle
          fetch-depth: 0

      - name: Setup local maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Run Shell Script
        run: |
          ./.ci/generate-website.sh ${{ inputs.version }}

      - name: Checkout checkstyle.github.io repo
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/checkstyle.github.io
          token: ${{ secrets.PAT }}
          path: .ci-temp/checkstyle.github.io/

      - name: Commit and Push to checkstyle.github.io repo
        run: |
          ./.ci/release-update-github-io.sh ${{ inputs.version }}
