#############################################################################
# GitHub Action to Upload '-all' Jar.
#
#############################################################################
name: "R: Upload '-all' Jar"
run-name: "R: Upload '-all' Jar ${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'POM version without (-SNAPSHOT)'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
    -${{ github.event.pull_request.number || github.ref }}-upload-all-jar
  cancel-in-progress: true

jobs:
  upload-all-jar:
    name: Upload '-all' jar ${{ inputs.version }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Setup local maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Run GitHub Update Script
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          ./.ci/release-upload-all-jar.sh ${{ inputs.version }}
