#############################################################################
# GitHub Action to Publish Release Notes to GitHub Release Page.
#
#############################################################################
name: "R: Update GitHub Page"
run-name: "R: Update GitHub Page ${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'POM version without (-SNAPSHOT)'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}
    -${{ github.event.pull_request.number || github.ref }}-update-github-page
  cancel-in-progress: true

jobs:
  update-github-page:
    name: Update GitHub Page ${{ inputs.version }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v6

      - name: Setup local maven cache
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Run Shell Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.ci/release-update-github-page.sh ${{ inputs.version }}
