#############################################################################
# GitHub Action to Create New Milestone and Issues in Other Repositories.
#
#############################################################################
name: "R: New Milestone, Create issues"
run-name: "R: New Milestone, Create issues ${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'POM version without (-SNAPSHOT)'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

permissions:
  contents: write
  issues: write

concurrency:
  group: ${{ github.workflow }}
    -${{ github.event.pull_request.number || github.ref }}-new-milestone-and-issues-in-other-repos
  cancel-in-progress: true

jobs:
  new-milestone-and-issues-in-other-repos:
    name: New Milestone, Create issues for ${{ inputs.version }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Download ncal
        run: |
          sudo apt-get install ncal

      - name: Setup local maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Close/Create Milestone
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          ./.ci/release-close-create-milestone.sh

      - name: Creation of issue in other Repositories
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          ./.ci/release-create-issues-in-other-repos.sh ${{ inputs.version }}
