#############################################################################
# GitHub Action to Run Perform goal of Maven Release plugin.
#
#############################################################################
name: "R: Maven Perform"
run-name: "R: Maven Perform ${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'POM version without (-SNAPSHOT)'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  maven-perform:
    name: Maven Perform ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: master

      - name: Setup local maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Configure GPG
        env:
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        run: |
          mkdir -p ~/.gnupg/
          echo "$GPG_SECRET_KEY" > ~/.gnupg/private.key
          gpg --batch --import ~/.gnupg/private.key
          chmod 600 ~/.gnupg/private.key
          chmod 700 ~/.gnupg

      - name: Prepare release settings
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        run: |
          ./.ci/release-create-maven-settings-xml.sh

      - name: Run Shell Script
        run: |
          ./.ci/release-maven-perform.sh ${{ inputs.version }}
