#####################################################################################
# GitHub Action to run checkstyle with:
#  config URL
#  target java file URL
#
# Output is printed in console terminal
#
#####################################################################################
name: Run-Checkstyle

on:
  workflow_dispatch:
    inputs:
      config-url:
        description: 'url to xml config'
        required: true
      java-source-url:
        description: 'url to java source'
        required: true
      compile:
        description: 'compile java by javac'
        required: true
        default: 'false'

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'checkstyle/checkstyle'
          latest: true
          fileName: 'checkstyle-*.*.*-all.jar'

      - name: Download config
        run: |
            curl --fail-with-body -X GET "${{ inputs.config-url }}" \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -o "config.xml"

      - name: Download target java source
        run: |
            curl --fail-with-body -X GET "${{ inputs.java-source-url }}" \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -o "Test.java"

      - name: Run checkstyle
        run: |
            pwd
            ls -la
            echo "Content of config.xml:"
            cat config.xml
            echo ""
            echo "Content of Test.java:"
            cat -n Test.java
            echo ""
            if [[ "${{ inputs.compile }}" == "true" ]]; then
              echo "javac Test.java:"
              javac Test.java
            fi
            echo ""
            JAR_NAME=$(find . -name "*-all.jar")
            echo "Executing: java -jar ""$JAR_NAME"" -c config.xml Test.java"
            java -jar "$JAR_NAME" -c config.xml Test.java
