#############################################################################
# GitHub action to set latest milestone on issue of merged PR.
#
#############################################################################
name: 'Milestone issue closed by PR'

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      commits:
        description: 'Json array of Github commits'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  issues: write
  pull-requests: write

jobs:
  set-milestone:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4

      - name: Set milestone on issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -z "${{inputs.commits}}" ]]; then
            COMMITS='${{ toJSON(github.event.commits) }}'
          else
            COMMITS="${{inputs.commits}}"
          fi
          ./.ci/set-milestone-on-referenced-issue.sh "$COMMITS"
