name: "shellcheck"

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # this execution should stay on GitHub actions due to time/ memory limits in other CI
  shellcheck:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install shellcheck

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Execute shellcheck
        run: shellcheck ./.ci/*.sh
