name: "no-exception testing"

on:
  pull_request:
    branches: [ master ]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install checkstyle
      run: mvn -e --no-transfer-progress clean install -Pno-validations

    - name: no-exception-openjdk9-lucene-and-others-javadoc
      run: ./.ci/no-exception-test.sh no-exception-lucene-and-others-javadoc

    - name: no-exception-cassandra-storm-tapestry-javadoc
      run: ./.ci/no-exception-test.sh no-exception-cassandra-storm-tapestry-javadoc

    - name: no-exception-hadoop-apache-groovy-scouter-javadoc
      run: ./.ci/no-exception-test.sh no-exception-hadoop-apache-groovy-scouter-javadoc

    - name: no-exception-openjdk9-lucene-and-other
      run: ./.ci/no-exception-test.sh no-exception-only-javadoc

    - name: non regression on XWiki project
      run: ./.ci/validation.sh no-error-xwiki
