#############################################################################
# GitHub Action to Update github.io
#
#############################################################################
name: "R: Update github.io"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: update github.io ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          repository: checkstyle/checkstyle
          fetch-depth: 0
      - name: Setup local maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
      - name: Run Shell Script
        run: |
          ./.ci/generate-website.sh ${{ inputs.version }}
      - name: Checkout checkstyle.github.io repo
        uses: actions/checkout@v3
        with:
          repository: checkstyle/checkstyle.github.io
          token: ${{ secrets.PAT }}
          path: .ci-temp/checkstyle.github.io/
      - name: Commit and Push to checkstyle.github.io repo
        run: |
          ./.ci/push-website-to-github-io.sh ${{ inputs.version }}
