#############################################################################
# GitHub Action to Update github.io
#
#############################################################################
name: "R: Update github.io"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true
jobs:
  update:
    name: update github.io ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Shell Script
        run: |
          ./.ci/update-github-io.sh ${{ github.event.inputs.version }}
      - name: Commit and Push
        run: |
          cd .ci-temp/checkstyle.github.io
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add . && git commit -m "release ${{ github.event.inputs.version }}"
          echo "Push site content to remote ..." 
          echo "We do force to avoid history changes as github.io shows only HEAD." 
          git push origin --force 
