#############################################################################
# GitHub Action to Push Release Notes.
#
#############################################################################
name: "R: Push Release Notes"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  releasenotes:
    name: Push releasenotes ${{ inputs.version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Setup local maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
      - name: Run Shell Script
        env:
          READ_ONLY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.ci/update-releasenotesxml.sh ${{ inputs.version }}
      - name: Commit and Push
        run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add . && git commit -m "doc: release notes for ${{ inputs.version }}"
            git push origin master
