#############################################################################
# GitHub Action to Upload '-all' Jar.
# It is part of .github/workflows/new-milestone-and-issue-in-other-repo.yml
#
#############################################################################
name: "R: GitHub Upload Jar only"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true
jobs:
  github:
    name: Upload '-all' jar to Github for ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2

      - name: Run GitHub Update Script
        run: |
          ./.ci/upload-all-jar.sh ${{ github.event.inputs.version }}
